name: 'Publish Docker'
author: 'Ramz'
branding:
  icon: 'anchor'
  color: 'orange'
description: 'Uses git tag as docker tag and pushes the container in a multi container repo'
inputs:
  name:
    description: 'The name of the image you would like to push'
    required: true
  version:
    description: 'Name of the version of image you would like to build'
    required: true
  username:
    description: 'The login username for the registry'
    required: true
  password:
    description: 'The login password for the registry'
    required: true
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
  snapshot:
    description: 'Use snapshot to push an additional image'
    required: false
  dockerfile:
    description: 'Use dockerfile when you would like to explicitly build a Dockerfile'
    required: false
  workdir:
    description: 'Use workdir when you would like to change the directory for building'
    required: false
  buildargs:
    description: 'Use buildargs when you want to pass a list of environment variables as build-args'
    required: false
  cache:
    description: 'Use cache when you have big images, that you would only like to build partially'
    required: false
  tag_names:
    description: 'Use tag_names when you want to push tags/release by their git name'
    required: false
  tags:
    description: 'tags to push'
    required: false
  tag_semver:
    description: 'Push semver docker tags. e.g. image:1.2.3, image:1.2, image:1'
    required: false
outputs:
  tag:
    description: 'Is the tag, which was pushed'
  snapshot-tag:
    description: 'Is the tag that is generated by the snapshot-option and pushed'
  digest:
    description: 'Is the digest of the image, which was pushed'
runs:
  using: 'docker'
  image: 'Dockerfile'
