trigger:
- master

pool: Default

variables:
  - group: registry

name: ubuntu-bionic-r$(Rev:r)
steps:
  - script: make release-ubuntu CONTAINER_BUILDER=img REGISTRY_USER=$(REGISTRY_USER) REGISTRY_PASS=$(REGISTRY_PASS) BRANCH=$(Build.SourceBranchName) IMAGE_VERSION=$(Build.BuildNumber)
    displayName: 'Release Ubuntu Base Image'
