name: Alpine 3.10 Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'alpine/3.10/**'
      - '.github/workflows/alpine-3.10.yml'

env:
  IMAGE_NAME: base
  IMAGE_VERSION: 3.10-alpine-r${{github.run_number}}

jobs:

  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build --file alpine/3.10/Dockerfile
            --label "org.opencontainers.image.source=https://github.com/techniumlabs/containers/alpine/3.10"
            --label "org.opencontainers.image.revision=${{github.sha}}"
            --label "org.opencontainers.image.vendor=techniumlabs"
            --build-arg MAINTAINER=${MAINTAINER} --build-arg TIMEZONE=${TIMEZONE} --tag image alpine/3.10

        env:
          MAINTAINER: devops@techniumlabs.com
          TIMEZONE: Australia/Sydney

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_VERSION=$IMAGE_VERSION

          docker tag image $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION
