name: Alpine 3.10 Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build alpine/3.10 --file Dockerfile --build-arg MAINTAINER=${MAINTAINER} --build-arg TIMEZONE=${TIMEZONE} --tag base:alpine-3.10-${GITHUB_RUN_NUMBER}
      env:
        MAINTAINER: devops@techniumlabs.com
        TIMEZONE: Australia/Sydney
