name: alpine-3.10
on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'alpine/3.10/**'
      - '.github/workflows/alpine-3.10.yml'

env:
  IMAGE_DIR: alpine/3.10
  IMAGE_NAME: alpine
  IMAGE_VERSION: 3.10-r${{github.run_number}}
  IMAGE_REGISTRY: docker.pkg.github.com/techniumlabs
  IMAGE_REPOSITORY: containers
  MAINTAINER: devops@techniumlabs.com
  TIMEZONE: Australia/Sydney

jobs:

  # Push image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
      - name: Publish to registry
        uses: ./action
        with:
          name: docker.pkg.github.com/techniumlabs
          username: ${{ github.actor }}
          password: ${{ secrets. GITHUB_TOKEN }}
