name: clair 2.1 Image

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
    paths:
      - 'clair/2.1/**'
      - '.github/workflows/clair-2.1.yml'
    # Publish `v2.1.2` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: clair
  IMAGE_VERSION: 2.1-alpine-r${{github.run_number}}
  IMAGE_REGISTRY: docker.pkg.github.com/techniumlabs
  IMAGE_REPOSITORY: containers

jobs:

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build --file clair/2.1/Dockerfile
            --label "org.opencontainers.image.source=https://github.com/techniumlabs/containers/clair/2.1"
            --label "org.opencontainers.image.revision=${{github.sha}}"
            --label "org.opencontainers.image.vendor=techniumlabs"
            --build-arg IMAGE_REGISTRY=${IMAGE_REGISTRY}
            --build-arg IMAGE_REPOSITORY=${IMAGE_REPOSITORY}
            --build-arg MAINTAINER=${MAINTAINER} --build-arg TIMEZONE=${TIMEZONE} --tag image clair/2.1

        env:
          MAINTAINER: devops@techniumlabs.com
          TIMEZONE: Australia/Sydney

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_VERSION=$IMAGE_VERSION

          docker tag image $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION

      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to docker hub
        run: |
          IMAGE_ID=techniumlabs/$IMAGE_NAME

          echo IMAGE_ID=$IMAGE_ID
          echo IMAGE_VERSION=$IMAGE_VERSION

          docker tag image $IMAGE_ID:$IMAGE_VERSION
          docker push $IMAGE_ID:$IMAGE_VERSION