name: php-fpm-7.3
on:
  create:
  push:
    branches:
      - master
    paths:
      - 'php-fpm/7.3/**'
      - '.github/workflows/php-fpm-7.3.yml'

env:
  IMAGE_VERSION: 7.3-r${{github.run_number}}
  IMAGE_REGISTRY: registry.hub.docker.com
  IMAGE_REPOSITORY: techniumlabs
  MAINTAINER: devops@techniumlabs.com
  TIMEZONE: Australia/Sydney

jobs:
  ci-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Publish to registry
        uses: ./action
        with:
          name: php-fpm
          registry: docker.pkg.github.com/techniumlabs/containers
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: php-fpm/7.3
          buildargs: IMAGE_REGISTRY,IMAGE_REPOSITORY,MAINTAINER,TIMEZONE
          tags: 7.3-ci-build-r${{ github.sha }}
  release-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && startswith(github.ref, 'refs/tags/php-fpm/7.3/')
    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker registry
        uses: ./action
        with:
          name: techniumlabs/php-fpm
          version: '7.3'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: php-fpm/7.3
          buildargs: IMAGE_REGISTRY,IMAGE_REPOSITORY,MAINTAINER,TIMEZONE
          tag_names: true