name: traefik-2.1
on:
  create:
  push:
    branches:
      - master
    paths:
      - 'traefik/2.1/**'
      - '.github/workflows/traefik-2.1.yml'

env:
  IMAGE_VERSION: 2.1-r${{github.run_number}}
  IMAGE_REGISTRY: registry.hub.docker.com
  IMAGE_REPOSITORY: techniumlabs
  MAINTAINER: devops@techniumlabs.com
  TIMEZONE: Australia/Sydney

jobs:
  ci-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Publish to registry
        uses: ./action
        with:
          name: traefik
          registry: docker.pkg.github.com/techniumlabs/containers
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          workdir: traefik/2.1
          buildargs: IMAGE_REGISTRY,IMAGE_REPOSITORY,MAINTAINER,TIMEZONE
          tags: 2.1-ci-build-r${{ github.sha }}
  release-build:
    runs-on: ubuntu-latest
    if: github.event_name == 'create' && startswith(github.ref, 'refs/tags/traefik/2.1/')
    steps:
      - uses: actions/checkout@v2
      - name: Publish to docker registry
        uses: ./action
        with:
          name: techniumlabs/traefik
          version: '2.1'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: traefik/2.1
          buildargs: IMAGE_REGISTRY,IMAGE_REPOSITORY,MAINTAINER,TIMEZONE
          tag_names: true